site_name: .fmbot
repo_url: https://github.com/fmbot-discord/fmbot
repo_name: fmbot
site_description: Documentation for fmbot, a Discord Last.FM bot with various 3rd party integrations.
google_analytics: ['UA-157903776-1', 'fmbot.xyz']
theme:
  name: 'material'
  palette:
    scheme: preference
markdown_extensions:
  - admonition
  - toc:
      permalink: true
nav:
  - 'Introduction': 'index.md'
  - 'Commands':
    - 'Getting started': 'commands/index.md'
    - 'Tracks': 'commands/tracks.md'
    - 'Albums': 'commands/albums.md'
    - 'Artists': 'commands/artists.md'
    - 'Featured': 'commands/featured.md'
    - 'Friends': 'commands/friends.md'
    - 'Spotify': 'commands/spotify.md'
    - 'Genius': 'commands/genius.md'
    - 'YouTube': 'commands/youtube.md'
    - 'Guild settings': 'commands/guildsettings.md'
    - 'Miscellaneous': 'commands/misc.md'
  - 'FAQ': 'faq.md'
  - 'Selfhosting': 'setup.md'
  - 'Invite the bot': https://discordapp.com/oauth2/authorize?client_id=356268235697553409&scope=bot&permissions=52288