site_name: .fmbot
repo_url: https://github.com/fmbot-discord/fmbot
repo_name: fmbot
site_description: Welcome to .fmbot! .fmbot is a social Discord bot that provides music statistics for you, your friends, and your fellow server members.
theme:
  name: 'material'
  custom_dir: docs/overrides
  palette:
    scheme: preference
  logo: img/logo.png
  favicon: img/favicon.png
markdown_extensions:
  - admonition
  - toc:
      permalink: true

extra_javascript:
  - javascript/analytics.js

nav:
  - 'Introduction': 'index.md'
  - 'Frequently Asked Questions': 'faq.md'
  - 'Commands':
    - 'Getting started': 'commands/index.md'
    - 'Albums': 'commands/albums.md'
    - 'Artists': 'commands/artists.md'
    - 'Crowns': 'commands/crowns.md'
    - 'Featured': 'commands/featured.md'
    - 'Friends': 'commands/friends.md'
    - 'Genius': 'commands/genius.md'
    - 'Plays': 'commands/plays.md'
    - 'Spotify': 'commands/spotify.md'
    - 'Tracks': 'commands/tracks.md'
    - 'Updating and indexing': 'commands/whoknows.md'
    - 'YouTube': 'commands/youtube.md'
    - 'Miscellaneous': 'commands/misc.md'
  - 'Server settings':
    - 'General': 'guildsettings/index.md'
    - 'WhoKnows': 'guildsettings/whoknowsettings.md'
    - 'Crowns': 'guildsettings/crownsettings.md'
    - 'Webhooks': 'guildsettings/webhooks.md'
  - 'Selfhosting': 'setup.md'
  - 'Privacy': 'privacy.md'
  - 'Donations': https://opencollective.com/fmbot/
  - 'Invite the bot': http://invite.fmbot.xyz/
